# Generated by Django 5.0.6 on 2024-06-15 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Startapp', '0002_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
